name: diy_boox
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get_it: ^7.2.0
  shared_preferences: ^2.1.0
  provider: ^6.0.5
  dio: ^5.1.1
  cached_network_image: ^3.2.3
  flutter_svg: ^2.0.4
  spring_button: ^2.0.0
  flutter_otp_text_field: ^1.1.1
  dropdown_button2: ^2.0.0
  syncfusion_flutter_charts: ^21.1.38
  flutter_slidable: ^2.0.0
  auto_size_text: ^3.0.0
  flutter_expanded_tile: ^0.3.7
  dotted_border: ^2.0.0+3
  m_toast: ^0.2.2
  linear_progress_bar: ^1.1.0
  dotted_line: ^3.2.2
  intl: ^0.18.1
  fluttertoast: ^8.2.2
  image_picker: ^1.0.2
  material_dialogs: ^1.1.4


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/illu/
    - assets/drawer_icons/
    - assets/invoices/

  fonts:
    - family: Sans
      fonts:
        - asset: fonts/SourceSansPro-Regular.ttf

