class GetBusinessInvoiceResponse {
  int id;
  String universalId;
  bool isInvoiceIdAutoGenerated;
  String invoicePrefix;
  int invoiceNextNumber;
  String invoiceTitle;
  String invoiceFooter;
  int invoicePaymentMethodId;
  String invoicePaymentDueTermsId;
  String newInvoiceNumber;
  bool isVatRegistered;
  String defaultTaxId;
  String defaultTaxName;
  int defaultTaxValue;

  GetBusinessInvoiceResponse({
    required this.id,
    required this.universalId,
    required this.isInvoiceIdAutoGenerated,
    required this.invoicePrefix,
    required this.invoiceNextNumber,
    required this.invoiceTitle,
    required this.invoiceFooter,
    required this.invoicePaymentMethodId,
    required this.invoicePaymentDueTermsId,
    required this.newInvoiceNumber,
    required this.isVatRegistered,
    required this.defaultTaxId,
    required this.defaultTaxName,
    required this.defaultTaxValue,
  });

  factory GetBusinessInvoiceResponse.fromJson(Map<String, dynamic> json) => GetBusinessInvoiceResponse(
    id: json["id"],
    universalId: json["universalId"],
    isInvoiceIdAutoGenerated: json["isInvoiceIdAutoGenerated"],
    invoicePrefix: json["invoicePrefix"],
    invoiceNextNumber: json["invoiceNextNumber"],
    invoiceTitle: json["invoiceTitle"],
    invoiceFooter: json["invoiceFooter"],
    invoicePaymentMethodId: json["invoicePaymentMethodId"],
    invoicePaymentDueTermsId: json["invoicePaymentDueTermsId"],
    newInvoiceNumber: json["newInvoiceNumber"],
    isVatRegistered: json["isVatRegistered"],
    defaultTaxId: json["defaultTaxId"],
    defaultTaxName: json["defaultTaxName"],
    defaultTaxValue: json["defaultTaxValue"],
  );

  Map<String, dynamic> toJson() => {
    "id": id,
    "universalId": universalId,
    "isInvoiceIdAutoGenerated": isInvoiceIdAutoGenerated,
    "invoicePrefix": invoicePrefix,
    "invoiceNextNumber": invoiceNextNumber,
    "invoiceTitle": invoiceTitle,
    "invoiceFooter": invoiceFooter,
    "invoicePaymentMethodId": invoicePaymentMethodId,
    "invoicePaymentDueTermsId": invoicePaymentDueTermsId,
    "newInvoiceNumber": newInvoiceNumber,
    "isVatRegistered": isVatRegistered,
    "defaultTaxId": defaultTaxId,
    "defaultTaxName": defaultTaxName,
    "defaultTaxValue": defaultTaxValue,
  };
}