class GetBusinessEstimateResponse {
  int id;
  String universalId;
  bool isEstimateIdAutoGenerated;
  String estimatePrefix;
  int estimateNextNumber;
  String estimateTitle;
  String estimateFooter;
  int estimatePaymentMethodId;
  String estimatePaymentDueTermsId;
  String newEstimateNumber;
  String defaultTaxId;
  int defaultTaxValue;
  String defaultTaxName;

  GetBusinessEstimateResponse({
    required this.id,
    required this.universalId,
    required this.isEstimateIdAutoGenerated,
    required this.estimatePrefix,
    required this.estimateNextNumber,
    required this.estimateTitle,
    required this.estimateFooter,
    required this.estimatePaymentMethodId,
    required this.estimatePaymentDueTermsId,
    required this.newEstimateNumber,
    required this.defaultTaxId,
    required this.defaultTaxValue,
    required this.defaultTaxName,
  });

  factory GetBusinessEstimateResponse.fromJson(Map<String, dynamic> json) => GetBusinessEstimateResponse(
    id: json["id"],
    universalId: json["universalId"],
    isEstimateIdAutoGenerated: json["isEstimateIdAutoGenerated"],
    estimatePrefix: json["estimatePrefix"],
    estimateNextNumber: json["estimateNextNumber"],
    estimateTitle: json["estimateTitle"],
    estimateFooter: json["estimateFooter"],
    estimatePaymentMethodId: json["estimatePaymentMethodId"],
    estimatePaymentDueTermsId: json["estimatePaymentDueTermsId"],
    newEstimateNumber: json["newEstimateNumber"],
    defaultTaxId: json["defaultTaxId"],
    defaultTaxValue: json["defaultTaxValue"],
    defaultTaxName: json["defaultTaxName"],
  );

  Map<String, dynamic> toJson() => {
    "id": id,
    "universalId": universalId,
    "isEstimateIdAutoGenerated": isEstimateIdAutoGenerated,
    "estimatePrefix": estimatePrefix,
    "estimateNextNumber": estimateNextNumber,
    "estimateTitle": estimateTitle,
    "estimateFooter": estimateFooter,
    "estimatePaymentMethodId": estimatePaymentMethodId,
    "estimatePaymentDueTermsId": estimatePaymentDueTermsId,
    "newEstimateNumber": newEstimateNumber,
    "defaultTaxId": defaultTaxId,
    "defaultTaxValue": defaultTaxValue,
    "defaultTaxName": defaultTaxName,
  };
}